"""Run all 20 LDBC SNB BI queries in Python over the full SF1 graph, reporting
per-query timing and parity against the Rust reference outputs in ``python/refs/``
(generated by ``LDBC_EMIT_JSON=<dir> cargo run --release --bin bi``).

Usage:
    python run_bi.py [snapshot_dir]
"""

import json
import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import loader  # noqa: E402
from props import days_from_civil  # noqa: E402
from bi import (  # noqa: E402
    q1, q2, q3, q4, q5, q6, q7, q8, q9, q10,
    q11, q12, q13, q14, q15, q16, q17, q18, q19, q20,
)

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_SNAPSHOT = os.path.join(
    REPO_ROOT,
    "data/bi-sf1-composite-merged-fk/graphs/csv/bi/composite-merged-fk/initial_snapshot",
)
REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "refs")


def _ref(name):
    with open(os.path.join(REFS, name)) as f:
        return json.load(f)


def _rows(result):
    return [list(r) for r in result]


def _round(rows, nd=6):
    return [[round(x, nd) if isinstance(x, float) else x for x in r] for r in rows]


def _specs(g, ctx):
    """Each spec: (id, description, run_fn, parity_fn). parity_fn(result) -> bool."""
    return [
        ("Q1", "posting summary",
         lambda: q1.q1_posting_summary(g, days_from_civil(2011, 12, 1)),
         lambda r: _rows(r[0]) == _ref("q1.rust.json")),
        ("Q2", "tag evolution",
         lambda: q2.q2_tag_evolution_native(g, days_from_civil(2012, 6, 1), "MusicalArtist"),
         lambda r: _rows(r) == _ref("q2.rust.json")),
        ("Q3", "popular topics",
         lambda: q3.q3_popular_topics(g, "Burma", "MusicalArtist"),
         # ref is [flid, title, fday, plid, count]; cross-check on flid+plid+count.
         lambda r: [[x[0], x[2], x[3]] for x in r] == [[x[0], x[3], x[4]] for x in _ref("q3.rust.json")]),
        ("Q4", "top creators",
         lambda: q4.q4_top_creators(g, days_from_civil(2010, 1, 29)),
         lambda r: _rows(r[0]) == _ref("q4.rust.json") and [[f] for f in r[1]] == _ref("q4forums.rust.json")),
        ("Q5", "active posters",
         lambda: q5.q5_active_posters(g, "Abbas_I_of_Persia"),
         lambda r: _rows(r) == _ref("q5.rust.json")),
        ("Q6", "authoritative users",
         lambda: q6.q6_authoritative(g, "Arnold_Schwarzenegger"),
         lambda r: _rows(r) == _ref("q6.rust.json")),
        ("Q7", "related topics",
         lambda: q7.q7_related_topics(g, "Enrique_Iglesias"),
         lambda r: _rows(r) == _ref("q7.rust.json")),
        ("Q8", "central person",
         lambda: q8.q8_central_person(g, "Che_Guevara", days_from_civil(2011, 7, 20), days_from_civil(2011, 7, 25)),
         lambda r: _rows(r) == _ref("q8.rust.json")),
        ("Q9", "thread initiators",
         lambda: q9.q9_thread_initiators(g, days_from_civil(2011, 10, 1), days_from_civil(2011, 10, 15)),
         lambda r: _rows(r) == _ref("q9.rust.json")),
        ("Q10", "experts in country",
         lambda: q10.q10_experts(g, 3470, "China", "MusicalArtist", 3, 4),
         lambda r: _rows(r) == _ref("q10.rust.json")),
        ("Q11", "friend triangles",
         lambda: q11.q11_friend_triangles(g, "India", days_from_civil(2012, 9, 29), days_from_civil(2013, 1, 1)),
         lambda r: [[r]] == _ref("q11.rust.json")),
        ("Q12", "message histogram",
         lambda: q12.q12_message_counts(g, days_from_civil(2010, 7, 22), 20, ["ar", "hu"]),
         lambda r: _rows(r) == _ref("q12.rust.json")),
        ("Q13", "zombies",
         lambda: q13.q13_zombies(g, "France", days_from_civil(2013, 1, 1), 2013 * 12 + 1),
         lambda r: _rows(r) == _ref("q13.rust.json")),
        ("Q14", "international dialog",
         lambda: q14.q14_international_dialog(g, "Chile", "Argentina"),
         lambda r: _rows(r) == _ref("q14.rust.json")),
        ("Q15", "weighted path",
         lambda: q15.q15_weighted_path(g, 14, 16, days_from_civil(2010, 11, 1), days_from_civil(2010, 12, 1)),
         lambda r: round(r, 6) == round(_ref("q15.rust.json")[0][0], 6)),
        ("Q16", "fake news",
         lambda: q16.q16_fake_news(
             g,
             q16.q16_param_result(g, "Meryl_Streep", days_from_civil(2012, 9, 16), 4),
             q16.q16_param_result(g, "Hank_Williams", days_from_civil(2012, 5, 8), 4)),
         lambda r: _rows(r) == _ref("q16.rust.json")),
        ("Q17", "information propagation",
         lambda: q17.q17_information_propagation(g, "Slavoj_Žižek", 4),
         lambda r: _rows(r) == _ref("q17.rust.json")),
        ("Q18", "friend recommendation",
         lambda: q18.q18_friend_recommendation(g, "Frank_Sinatra"),
         lambda r: _rows(r) == _ref("q18.rust.json")),
        ("Q19", "interaction path",
         lambda: q19.q19_interaction_path(g, 669, 648, ctx["interaction"]),
         lambda r: _round(_rows(r)) == _round(_ref("q19.rust.json"))),
        ("Q20", "recruitment",
         lambda: q20.q20_recruitment(g, "Falcon_Air", 66, ctx["study_wm"]),
         lambda r: _round(_rows(r)) == _round(_ref("q20.rust.json"))),
    ]


def _summary(qid, result):
    if qid == "Q11":
        return f"count={result}"
    if qid == "Q15":
        return f"{result:.4f}"
    if qid in ("Q1", "Q4"):
        return f"{len(result[0])} rows"
    return f"{len(result)} rows"


def main():
    snapshot = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SNAPSHOT
    if not os.path.isdir(os.path.join(snapshot, "dynamic")):
        sys.exit(f"no 'dynamic' dir under {snapshot}; pass the initial_snapshot path")

    print(f"Loading LDBC BI graph from {snapshot} ...", file=sys.stderr)
    t = time.perf_counter()
    g, _ = loader.load_bi_graph(snapshot)
    load_s = time.perf_counter() - t

    print("\n=== LDBC SNB BI — Python (rustychickpeas) ===")
    print(f"Loaded {g.node_count()} nodes / {g.relationship_count()} rels in {load_s:.1f}s")

    t = time.perf_counter()
    interaction = q19.build_interaction_map(g)
    studyat = q20.build_studyat(g)
    study_wm = q20.build_study_weight_map(g, studyat)
    setup_s = time.perf_counter() - t
    print(f"Precompute (Q19 interaction map + Q20 cohort weights) in {setup_s:.1f}s\n")
    ctx = {"interaction": interaction, "study_wm": study_wm}

    print(f"{'Query':<6}{'Description':<26}{'Result':>11}{'Time':>11}  Parity")
    print("-" * 66)
    passed = checked = 0
    for qid, label, run_fn, parity_fn in _specs(g, ctx):
        t = time.perf_counter()
        result = run_fn()
        dt = (time.perf_counter() - t) * 1000
        try:
            ok = parity_fn(result)
            status = "ok" if ok else "FAIL"
            checked += 1
            passed += bool(ok)
        except FileNotFoundError:
            status = "n/a"
        print(f"{qid:<6}{label:<26}{_summary(qid, result):>11}{dt:>9.1f}ms  {status}")

    print("-" * 66)
    print(f"{passed}/{checked} queries match the Rust reference  "
          f"(load {load_s:.1f}s + precompute {setup_s:.1f}s)")


if __name__ == "__main__":
    main()
