"""Run the ported LDBC SNB Interactive (IC/IS) queries in Python over the full SF1
graph, reporting per-query timing and parity against the Rust reference outputs in
``python/refs/`` (generated by ``LDBC_EMIT_JSON=<dir> cargo run --release --bin ic``).

Parameters come from ``python/refs/seeds.json`` (the seeds ``pick_seeds`` chose), so
both engines run identical params. Persons are addressed by their external id.

Usage:
    python run_ic.py [snapshot_dir]

Covered so far: IS2, IS3, IS5, IC2, IC9, IC13, IC14. IS1/IC1 (need firstName/
lastName, not yet loaded) and the remaining loader-backed tier are pending.
"""

import json
import os
import statistics
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import loader  # noqa: E402
from props import days_from_civil  # noqa: E402
from ic import (  # noqa: E402
    is1, is2, is3, is5, is6, is7,
    ic1, ic2, ic3, ic4, ic6, ic8, ic9, ic12, ic13, ic14,
)
from rustychickpeas import Direction  # noqa: E402

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_SNAPSHOT = os.path.join(
    REPO_ROOT,
    "data/bi-sf1-composite-merged-fk/graphs/csv/bi/composite-merged-fk/initial_snapshot",
)
REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "refs")


def _ref(name):
    with open(os.path.join(REFS, name)) as f:
        return json.load(f)


def _eid(g, node):
    return g.get_property(node, "id")


def _specs(g, seeds, ctx):
    """Each spec: (id, description, run_fn, project_fn) where project_fn(result)
    maps the query result to the comparable rows the Rust side emits."""
    person, person_b, max_day = seeds["person"], seeds["person_b"], seeds["max_day"]
    first_name, seed_tag, seed_class = seeds["first_name"], seeds["seed_tag"], seeds["seed_class"]
    ic4_start, ic4_dur = seeds["ic4_start"], seeds["ic4_dur"]
    seed_post, roots = ctx["seed_post"], ctx["roots"]

    def is5_run():
        msgs = is2.is2_recent_of_person(g, person, max_day)
        creator = is5.is5_message_creator(g, msgs[0][0]) if msgs else None
        return creator

    return [
        ("IS1", "profile",
         lambda: is1.is1_profile(g, person),
         lambda r: [[r[0], r[1]]]),
        ("IC1", "friends by name",
         lambda: ic1.ic1_friends_by_name(g, person, first_name),
         lambda r: [[d, ln, _eid(g, p)] for (p, d, ln) in r]),
        ("IC3", "two-country friends",
         lambda: ic3.ic3_friends_two_countries(
             g, person, "China", "Germany", days_from_civil(2010, 1, 1), 1500),
         lambda r: [[_eid(g, p), xc, yc] for (p, xc, yc) in r]),
        ("IC4", "new topics",
         lambda: ic4.ic4_new_topics(g, person, ic4_start, ic4_dur),
         lambda r: [[g.prop_str(t, "name"), c] for (t, c) in r]),
        ("IC12", "expert search",
         lambda: ic12.ic12_expert_search(g, person, seed_class),
         lambda r: [[_eid(g, f), c] for (f, c, _names) in r]),
        ("IS2", "recent of person",
         lambda: is2.is2_recent_of_person(g, person, max_day),
         lambda r: [[ms] for (_id, ms) in r]),
        ("IS3", "friends",
         lambda: is3.is3_friends(g, person),
         lambda r: [[e] for e in sorted(_eid(g, f) for f in r)]),
        ("IS5", "message creator",
         is5_run,
         lambda r: [[_eid(g, r) if r is not None else -1]]),
        ("IC2", "recent messages",
         lambda: ic2.ic2_recent_messages(g, person, max_day),
         lambda r: [[ms] for (_id, ms) in r]),
        ("IC9", "fof messages",
         lambda: ic9.ic9_fof_messages(g, person, max_day),
         lambda r: [[ms] for (_id, ms) in r]),
        ("IC13", "shortest path",
         lambda: ic13.ic13_shortest_path(g, person, person_b),
         lambda r: [[r]]),
        ("IC14", "weighted path",
         lambda: ic14.ic14_weighted_path(g, person, person_b, ctx["interaction"]),
         lambda r: [] if r is None else [[round(r, 6)]]),
        ("IC6", "tag co-occurrence",
         lambda: ic6.ic6_tag_cooccurrence(g, person, seed_tag),
         lambda r: [[g.prop_str(t, "name"), c] for (t, c) in r]),
        ("IC8", "recent replies",
         lambda: ic8.ic8_recent_replies(g, person),
         lambda r: [[ms] for (_id, ms) in r]),
        ("IS6", "forum of message",
         lambda: is6.is6_forum_of_message(g, seed_post, roots) if seed_post is not None else None,
         lambda r: [] if r is None else [[_eid(g, r[0]), _eid(g, r[1])]]),
        ("IS7", "replies",
         lambda: is7.is7_replies(g, seed_post) if seed_post is not None else [],
         lambda r: [[ms, (_eid(g, ra) if ra != 0xFFFFFFFF else 0), int(k)]
                    for (_reply, ms, ra, k) in r]),
    ]


def main():
    snapshot = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SNAPSHOT
    if not os.path.isdir(os.path.join(snapshot, "dynamic")):
        sys.exit(f"no 'dynamic' dir under {snapshot}; pass the initial_snapshot path")

    print(f"Loading LDBC graph from {snapshot} ...", file=sys.stderr)
    t = time.perf_counter()
    g, _ = loader.load_bi_graph(snapshot)
    load_s = time.perf_counter() - t

    raw = _ref("seeds.json")
    seeds = {
        "person": g.node_with_label_property("Person", "id", raw["person"]),
        "person_b": g.node_with_label_property("Person", "id", raw["person_b"]),
        "max_day": raw["max_day"],
        "first_name": raw["first_name"],
        "seed_tag": raw["seed_tag"],
        "seed_class": raw["seed_class"],
        "ic4_start": raw["ic4_start"],
        "ic4_dur": raw["ic4_dur"],
    }

    print("\n=== LDBC SNB Interactive — Python (rustychickpeas) ===")
    print(f"Loaded {g.node_count()} nodes / {g.relationship_count()} rels in {load_s:.1f}s")

    t = time.perf_counter()
    interaction = ic14.build_interaction(g)
    # IS6/IS7 anchor on the seed's newest Post (same as the Rust runner); IS6 walks
    # the replyOf thread roots.
    posts = set(g.nodes_with_label("Post"))
    seed_post, best = None, None
    for m in g.neighbor_ids(seeds["person"], Direction.Outgoing, ["hasCreator"]):
        if m in posts:
            mms = g.get_property(m, "ms")
            if best is None or mms > best:
                best, seed_post = mms, m
    roots = g.roots_via("replyOf", Direction.Outgoing)
    setup_s = time.perf_counter() - t
    print(f"Precompute (IC14 interaction map + IS6 roots) in {setup_s:.1f}s\n")
    ctx = {"interaction": interaction, "seed_post": seed_post, "roots": roots}

    runs = int(os.environ.get("LDBC_RUNS", "5"))
    print(f"{'Query':<7}{'Description':<22}{'Time':>12}  Parity")
    print("-" * 52)
    passed = checked = 0
    for qid, label, run_fn, project_fn in _specs(g, seeds, ctx):
        result = run_fn()
        times = []
        for _ in range(runs):
            t = time.perf_counter()
            run_fn()
            times.append((time.perf_counter() - t) * 1000.0)
        dt = statistics.median(times)
        try:
            ok = project_fn(result) == _ref(f"{qid.lower()}.rust.json")
            status = "ok" if ok else "FAIL"
            checked += 1
            passed += bool(ok)
        except FileNotFoundError:
            status = "n/a"
        print(f"{qid:<7}{label:<22}{dt:>10.1f}ms  {status}")

    print("-" * 52)
    print(f"{passed}/{checked} queries match the Rust reference  "
          f"(median of {runs}; load {load_s:.1f}s + precompute {setup_s:.1f}s)")


if __name__ == "__main__":
    main()
