"""Run the ported LDBC SNB Interactive (IC/IS) queries in Python over the full SF1
graph, reporting per-query timing and parity against the Rust reference outputs in
``python/refs/`` (generated by ``LDBC_EMIT_JSON=<dir> cargo run --release --bin ic``).

Parameters come from ``python/refs/seeds.json`` (the seeds ``pick_seeds`` chose), so
both engines run identical params. Persons are addressed by their external id.

Usage:
    python run_ic.py [snapshot_dir]

Covered so far: IS2, IS3, IS5, IC2, IC9, IC13, IC14. IS1/IC1 (need firstName/
lastName, not yet loaded) and the remaining loader-backed tier are pending.
"""

import json
import os
import statistics
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import loader  # noqa: E402
from ic import is2, is3, is5, ic2, ic9, ic13, ic14  # noqa: E402

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_SNAPSHOT = os.path.join(
    REPO_ROOT,
    "data/bi-sf1-composite-merged-fk/graphs/csv/bi/composite-merged-fk/initial_snapshot",
)
REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "refs")


def _ref(name):
    with open(os.path.join(REFS, name)) as f:
        return json.load(f)


def _eid(g, node):
    return g.get_property(node, "id")


def _specs(g, seeds, ctx):
    """Each spec: (id, description, run_fn, project_fn) where project_fn(result)
    maps the query result to the comparable rows the Rust side emits."""
    person, person_b, max_day = seeds["person"], seeds["person_b"], seeds["max_day"]

    def is5_run():
        msgs = is2.is2_recent_of_person(g, person, max_day)
        creator = is5.is5_message_creator(g, msgs[0][0]) if msgs else None
        return creator

    return [
        ("IS2", "recent of person",
         lambda: is2.is2_recent_of_person(g, person, max_day),
         lambda r: [[ms] for (_id, ms) in r]),
        ("IS3", "friends",
         lambda: is3.is3_friends(g, person),
         lambda r: [[e] for e in sorted(_eid(g, f) for f in r)]),
        ("IS5", "message creator",
         is5_run,
         lambda r: [[_eid(g, r) if r is not None else -1]]),
        ("IC2", "recent messages",
         lambda: ic2.ic2_recent_messages(g, person, max_day),
         lambda r: [[ms] for (_id, ms) in r]),
        ("IC9", "fof messages",
         lambda: ic9.ic9_fof_messages(g, person, max_day),
         lambda r: [[ms] for (_id, ms) in r]),
        ("IC13", "shortest path",
         lambda: ic13.ic13_shortest_path(g, person, person_b),
         lambda r: [[r]]),
        ("IC14", "weighted path",
         lambda: ic14.ic14_weighted_path(g, person, person_b, ctx["interaction"]),
         lambda r: [] if r is None else [[round(r, 6)]]),
    ]


def main():
    snapshot = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SNAPSHOT
    if not os.path.isdir(os.path.join(snapshot, "dynamic")):
        sys.exit(f"no 'dynamic' dir under {snapshot}; pass the initial_snapshot path")

    print(f"Loading LDBC graph from {snapshot} ...", file=sys.stderr)
    t = time.perf_counter()
    g, _ = loader.load_bi_graph(snapshot)
    load_s = time.perf_counter() - t

    raw = _ref("seeds.json")
    seeds = {
        "person": g.node_with_label_property("Person", "id", raw["person"]),
        "person_b": g.node_with_label_property("Person", "id", raw["person_b"]),
        "max_day": raw["max_day"],
    }

    print("\n=== LDBC SNB Interactive — Python (rustychickpeas) ===")
    print(f"Loaded {g.node_count()} nodes / {g.relationship_count()} rels in {load_s:.1f}s")

    t = time.perf_counter()
    interaction = ic14.build_interaction(g)
    setup_s = time.perf_counter() - t
    print(f"Precompute (IC14 interaction map) in {setup_s:.1f}s\n")
    ctx = {"interaction": interaction}

    runs = int(os.environ.get("LDBC_RUNS", "5"))
    print(f"{'Query':<7}{'Description':<22}{'Time':>12}  Parity")
    print("-" * 52)
    passed = checked = 0
    for qid, label, run_fn, project_fn in _specs(g, seeds, ctx):
        result = run_fn()
        times = []
        for _ in range(runs):
            t = time.perf_counter()
            run_fn()
            times.append((time.perf_counter() - t) * 1000.0)
        dt = statistics.median(times)
        try:
            ok = project_fn(result) == _ref(f"{qid.lower()}.rust.json")
            status = "ok" if ok else "FAIL"
            checked += 1
            passed += bool(ok)
        except FileNotFoundError:
            status = "n/a"
        print(f"{qid:<7}{label:<22}{dt:>10.1f}ms  {status}")

    print("-" * 52)
    print(f"{passed}/{checked} queries match the Rust reference  "
          f"(median of {runs}; load {load_s:.1f}s + precompute {setup_s:.1f}s)")


if __name__ == "__main__":
    main()
